def intro():
    print("\t WELCOME TO ... TIC TAC TOE ...\n")
    print("      |      |      ")
    print("   1  |   2  |   3  ")
    print("______|______|______")
    print("      |      |      ")
    print("   4  |   5  |   6  ")
    print("______|______|______")
    print("      |      |      ")
    print("   7  |   8  |   9  ")
    print("      |      |      ")
    print("\nInstructions :")
    print("    For 1st player     -->  X")
    print("    For second player  -->  O")
    print("    Chose, any number between 1 to 9 :\n")
